"""add application table and update thread

Revision ID: 812db957037d
Revises: 92ae4c8d0e00
Create Date: 2025-12-19 10:36:24.881075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '812db957037d'
down_revision = '92ae4c8d0e00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    device_type_enum = postgresql.ENUM('web', 'mobile_app', name='devicetype')
    device_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Add nullable first so existing rows can be backfilled before NOT NULL.
    op.add_column('threads', sa.Column('device_type', device_type_enum, nullable=True))
    op.add_column('threads', sa.Column('application_id', sa.UUID(), nullable=True))

    # Backfill from legacy `platform` column (best-effort mapping).
    # - `webuddhist_app` previously represented the mobile app.
    # - Everything else maps to `web`.
    op.execute(
        """
        UPDATE threads
        SET device_type = CASE
            WHEN platform = 'webuddhist_app' THEN 'mobile_app'::devicetype
            ELSE 'web'::devicetype
        END
        WHERE device_type IS NULL
        """
    )

    op.alter_column('threads', 'device_type', nullable=False)
    op.create_foreign_key(
        'threads_application_id_fkey',
        'threads',
        'applications',
        ['application_id'],
        ['id'],
    )
    op.drop_column('threads', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add legacy column in a way that won't fail if threads has rows.
    platform_enum = postgresql.ENUM('sherab', 'webuddhist', 'webuddhist_app', name='platform')
    platform_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('threads', sa.Column('platform', platform_enum, nullable=True))

    # Best-effort: map device_type back to platform (lossy).
    op.execute(
        """
        UPDATE threads
        SET platform = CASE
            WHEN device_type = 'mobile_app' THEN 'webuddhist_app'::platform
            ELSE 'webuddhist'::platform
        END
        WHERE platform IS NULL
        """
    )
    op.alter_column('threads', 'platform', nullable=False)

    op.drop_constraint('threads_application_id_fkey', 'threads', type_='foreignkey')
    op.drop_column('threads', 'application_id')
    op.drop_column('threads', 'device_type')
    op.drop_table('applications')

    device_type_enum = postgresql.ENUM('web', 'mobile_app', name='devicetype')
    device_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

