"""create chats table

Revision ID: f77ea0f8d113
Revises: e66ada07112d
Create Date: 2025-12-16 16:02:11.531522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77ea0f8d113'
down_revision = 'e66ada07112d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

